### ISSUE TITLE
Poor error message for feed limit reached

### ISSUE THREAD

**Issue by bassdread** [adafruit/io-client-python#10]
If you attempt the following, when you have hit the maximum number of feeds allowed on your account:

```
aio.send('oneFeedTooMany', 6)
```

You get a generic error "Adafruit_IO.errors.RequestError: Adafruit IO request failed: 422 Unprocessable Entity".

This lost an hour while I attempted to debug it. Need a better error message if possible in the Python lib.

**Comment by baracudaz** [comment]
Same here. It looks like current limit is *10* feeds. Is this documented anywhere? Any ideas how to overcome the limit? Thanks!

**Comment by jwcooper** [comment]
Added: 9de0fe9
