### ISSUE TITLE
No module named Adafruit_IO

### ISSUE THREAD

**Issue by tlmyasirs** [adafruit/io-client-python#13]
i have installed and used the line 

from Adafruit_IO import Client

but im getting an error as 

pi@raspberrypi:~ $ python ser-read-ada2.py
Traceback (most recent call last):
  File "ser-read-ada2.py", line 4, in <module>
    from Adafruit_IO import Client
ImportError: No module named Adafruit_IO

**Comment by tlmyasirs** [comment]
i was running at a wrong place i didnt know that
now im fixed

**Comment by bha14ur** [comment]
i am getting the same error..please help me..
i am running the code from where i put my python file

**Comment by bha14ur** [comment]
> i was running at a wrong place i didnt know that
> now im fixed

wrong place means ..???
where we have to run this code?
because i am getting the same error. please help me.
