### ISSUE TITLE
Break out errors into explicit types

### ISSUE THREAD

**Issue by tdicola** [adafruit/io-client-python#18]
In particular break out connection attempt failed errors (non-zero RC in connect callback), and the disconnect errors (non-zero RC in disconnect callback) into explicit error types that inherit from a common error base.  This way it's easier to catch errors like unexpected disconnects and retry connecting to the service.

**Comment by brentru** [comment]
This issue is being worked on in the https://github.com/adafruit/io-client-python/tree/mqtt_error_handling branch.

**Comment by brentru** [comment]
Closing...added into `api-v2` branch for staging
