### ISSUE TITLE
Adafruit MQTT not connecting

### ISSUE THREAD

**Issue by blazexak** [adafruit/io-client-python#23]
Hi,

I have modified the mqtt_client.py to subscribe to my own feed on Adafruit.io. Sometimes it would work without a problem, but at the moment when I run the script, it literally prints out nothing, I am not sure if it even successfully being connected to the server. I actually encountered this problem a couple months back, but at the moment I am working on a project where I need it to connect successfully at all time. 

I am a very very begineer python user and have been programming in C++ the whole time, so I might have miss something obvious. I have uploaded the code, but I only changed three lines which are subscribing to my own feed, and setting the Adafruit id and user name. 

Would someone be able to give me some pointers on what went wrong? At the moment, Adafruit IO only allows 2 requests per second. Could it be I might have accidentally exceed the limit, and temporary banned from the server?

 Thank you for your time in advance.

**Comment by jwcooper** [comment]
Hi, could you post this to our forum? It will get a lot more people to look at it and hopefully offer suggestions. Thanks!

https://forums.adafruit.com/viewforum.php?f=56

**Comment by GUNJAN10** [comment]
Did we solve this issue ? If yes, kindly suggest since I am facing the same issue.
