### ISSUE TITLE
AIO API currently returns 422 when throttled, not 429

### ISSUE THREAD

**Issue by cwbooth5** [adafruit/io-client-python#35]
https://github.com/adafruit/io-client-python/blob/75a84c56c23235e76a99305284dccc4bf900a021/Adafruit_IO/client.py#L64

The client is checking for a 429 specifically, but I am being throttled and the HTTP status code being raised to the caller is a 422/Unprocessable Entity. Is the AIO web server returning the incorrect status code right now or is it correct and Client() should be raising your ThrottlingError exception class?

The 429 is the correct status to be sending back to my client, but I'm not sure which side of this is 'wrong'.

**Comment by brentru** [comment]
@cwbooth5  Thanks for the report, this was an issue from the API, HTTP throttle errors should return 429 now. Closing...
