### ISSUE TITLE
Connecting with SSL/TLS

### ISSUE THREAD

**Issue by mr-bjerre** [adafruit/io-client-python#37]
Is it possible to connect securely using SSL/TLS like in this [post](https://io.adafruit.com/blog/security/2016/07/05/adafruit-io-security-esp8266/)? As far as I can see this package uses an insecure MQTT client on port 1883.

**Comment by brentru** [comment]
Default support for SSL/TLS will be added to the next release of this library and is currently implemented in the [secure mqtt branch](https://github.com/adafruit/io-client-python/tree/secure-mqtt).
