### ISSUE TITLE
api-v2: only send values that are explicitly set when creating new models

### ISSUE THREAD

**Issue by jwcooper** [adafruit/io-client-python#43]
See example below, the only values that should be sent are "name" and "key" below. The others should not be set.

Defaults are set in model.py:
`Feed.__new__.__defaults__   = tuple(None for x in FEED_FIELDS)`

>>> from Adafruit_IO import Client, Feed
>>> feed = Feed(name="June Python", key="june-python")
>>> feed
Feed(name='June Python', key='june-python', description=None, unit_type=None, unit_symbol=None, history=None, visibility=None, license=None, status_notify=None, status_timeout=None)
>>>

**Comment by brentru** [comment]
**Patch:** https://github.com/adafruit/io-client-python/blob/api-v2/Adafruit_IO/model.py#L78

**Notes:** Explicitly declared feed values for `history` and `visibility`. Other feed fields are initialized to `None`(handled by the API).

**Output** 
```
>>> from Adafruit_IO import Feed, Client
>>> ADAFRUIT_IO_USERNAME = 'user'
>>> ADAFRUIT_IO_KEY = 'key'
>>> aio = Client(ADAFRUIT_IO_USERNAME, ADAFRUIT_IO_KEY)
>>> feed = Feed(name="test-feed-gen2")
>>> response = aio.create_feed(feed)
>>> print('sending 42 to test-feed-gen2')
sending 42 to test-feed-gen2
>>> aio.send_data('test-feed-gen2', 42)
Data(created_epoch=1530043278, created_at='2018-06-26T20:01:18Z', updated_at=None, value='42', completed_at=None, feed_id=828101, expiration='2018-08-25T20:01:18Z', position=None, id='0DX9MDRZ4FQ8DX4KEBYS7HPKVC')
>>> data = aio.receive('test-feed-gen2')
>>> print('Retrieved value from test-feed-gen2 has attributes: {0}'.format(data))
Retrieved value from test-feed-gen2 has attributes: Data(created_epoch=None, created_at='2018-06-26T20:01:18Z', updated_at='2018-06-26T20:01:18Z', value='42', completed_at=None, feed_id=828101, expiration='1535227278.0', position=None, id='0DX9MDRZ4FQ8DX4KEBYS7HPKVC')
```
