### ISSUE TITLE
Default to mqtts for the mqtt components, port 8883

### ISSUE THREAD

**Issue by jwcooper** [adafruit/io-client-python#5]

**Comment by brentru** [comment]
Tackling this issue in: https://github.com/adafruit/io-client-python/tree/secure-mqtt

**Comment by brentru** [comment]
Merged, and closing. `api-v2` branch now defaults to MQTT secure and will revert to MQTT (unsecure) if secure parameter is set to `false`:
`client = MQTTClient(ADAFRUIT_IO_USERNAME, ADAFRUIT_IO_KEY, **secure=False**)`
