### ISSUE TITLE
Docs on Readthedocs not up to date

### ISSUE THREAD

**Issue by juax335** [adafruit/io-client-python#62]
Hey,

I was just checking out the adafruit-io client and it seems that the documentation on [Readthedocs](https://adafruit-io-python-client.readthedocs.io/en/latest/quickstart.html#basic-client-usage) is not up to date with `master/io-client-python/docs/quickstart.rst`. 

Thanks for having a look into it :)

**Comment by brentru** [comment]
Thanks for pointing this out, @juax335.

I triggered a rebuild on the ReadTheDocs from _master_ and verified the page against master. Looks good now.
