### ISSUE TITLE
Test and add support for lat/lon

### ISSUE THREAD

**Issue by jwcooper** [adafruit/io-client-python#9]
https://forums.adafruit.com/viewtopic.php?f=56&t=82937

**Comment by DaddyOh** [comment]
I'm interested in this feature for Lat/Long from python.

**Comment by tomber42** [comment]
is this solved?

**Comment by brentru** [comment]
Closing, successfully added support for Lat/Lon added to the experimental `api-v2` branch. This'll be added to master for the next release!
